const data = {
  BloodBanks: [
    [
      'Medant Blood Bank',
      'https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,f_auto,q_auto:eco,dpr_1/v1504670742/rpjgrkfsfexubeqvzotp.jpg',
      'Next available at Tomorrow 9 AM',
      '53 Street, Billionaires row',
      '4.1 (1202+)',
      '1',
    ],
    [
      'Indian Medical Association',
      'https://www.ima-india.org/ima/images/IMA%20LOGO.jpg',
      'Next available at Tomorrow 9 AM',
      '53 Street, Billionaires row',
      '4.1 (1202+)',
      '2',
    ],
    [
      'Apex hospital Blood bank',
      'https://img.freepik.com/free-vector/hospital-logo-design-vector-medical-cross_53876-136743.jpg',
      'Next available at Tomorrow 9 AM',
      '53 Street, Billionaires row',
      '4.1 (1202+)',
      '3',
    ],
    [
      'Dr Lal Pathlabs Blood bank',
      'https://img.freepik.com/free-vector/hospital-logo-design-vector-medical-cross_53876-136743.jpg',
      'Next available at Tomorrow 9 AM',
      '53 Street, Billionaires row',
      '4.1 (1202+)',
      '4',
    ],
    [
      'Dr Lal Pathlabs Blood bank',
      'https://images.vexels.com/media/users/3/282288/isolated/preview/9ded914031de73173d19cf30839fef76-hospital-surgery-logo.png',
      'Next available at Tomorrow 9 AM',
      '53 Street, Billionaires row',
      '4.1 (1202+)',
      '5',
    ],
    [
      'Medant Blood Bank',
      'https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,f_auto,q_auto:eco,dpr_1/v1504670742/rpjgrkfsfexubeqvzotp.jpg',
      'Next available at Tomorrow 9 AM',
      '53 Street, Billionaires row',
      '4.1 (1202+)',
      '6',
    ],
  ],

  Hospitals: [
    [
      'Aiims Delhi',
      'https://upload.wikimedia.org/wikipedia/commons/e/ee/AIIMS_New_Delhi.png',
      '600 beds available',
      '9 highly-equipped Operation Theaters',
      'OPD timings - 9am to 5pm',
      'Lajpat nagar',
      '1',
    ],
    [
      'Apollo Hospitals',
      'https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/Apollo_Hospitals_Logo.svg/800px-Apollo_Hospitals_Logo.svg.png',
      '600 beds available',
      '9 highly-equipped Operation Theaters',
      'OPD timings - 9am to 5pm',
      'Pitampura',
      '2',
    ],
    [
      'Nanavati Hospitals',
      'https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,f_auto,q_auto:eco,dpr_1/v1487919479/huc3hiiyxqceich8qcmx.jpg',
      '600 beds available',
      '9 highly-equipped Operation Theaters',
      'OPD timings - 9am to 5pm',
      'Pitampura',
      '3',
    ],
    [
      'Nanavati Hospitals',
      'https://images.vexels.com/media/users/3/282288/isolated/preview/9ded914031de73173d19cf30839fef76-hospital-surgery-logo.png',
      '600 beds available',
      '9 highly-equipped Operation Theaters',
      'OPD timings - 9am to 5pm',
      'Pitampura',
      '4',
    ],
  ],

  BloodTests: [
    [
      '1',
      'Pathkind labs-Complete Blood test',
      'https://www.ekarnal.com/wp-content/uploads/2019/08/PSC-Karnal-Dr.-Lal-Path-Labs.jpg',
      'Safe & Hygienic procedure',
      'Fastest Report Delivery',
      'Next available at Tomorrow 9 AM',
      '53rd Street, Billionaires row',
      '399',
    ],
    [
      '2',
      'SRL Labs- Blood test package',
      'https://upload.wikimedia.org/wikipedia/commons/6/61/SRL_Diagnostics_Logo.png',
      'Hassle-free booking & timely reports',
      'Safe and sanitized  sample collection',
      'Next available at Tomorrow 9 AM',
      '53rd Street, Billionaires row',
      '599',
    ],
    [
      '3',
      'Redcliffe Labs- Blood test',
      'https://bookface-images.s3.amazonaws.com/logos/23cb9a660c3a14cb8ab1a27d01d8e3a148194c35.png',
      'One-Stop Diagnostic Service Provider',
      '3600+ Routine & Specialized Tests',
      'Next available at Tomorrow 9 AM',
      '53rd Street, Billionaires row',
      '599',
    ],
    [
      '4',
      'Redcliffe Labs- Blood test',
      'https://img.freepik.com/free-vector/hospital-logo-design-vector-medical-cross_53876-136743.jpg',
      'One-Stop Diagnostic Service Provider',
      '3600+ Routine & Specialized Tests',
      'Next available at Tomorrow 9 AM',
      '53rd Street, Billionaires row',
      '599',
    ],
  ],

  Pharmacy: [
    [
      '1',
      'Mishra Pharmacy',
      'https://static.vecteezy.com/system/resources/previews/011/059/149/original/pharmacy-logo-medicine-symbol-vector.jpg',
      'Home delivery available',
      '12 Hours open- Sundays closed',
      'Next available at Tomorrow 9 AM',
      '53rd Street, Billionaires row',
      false,
    ],
    [
      '2',
      'Om Chemist',
      'https://static.vecteezy.com/system/resources/previews/015/394/284/original/medical-pharmacy-logo-design-vector.jpg',
      'Home delivery available',
      '12 Hours open- Sundays closed',
      'Next available at Tomorrow 9 AM',
      '53rd Street, Billionaires row',
      true,
    ],
    [
      '3',
      'Chauddhary Medical Store',
      'https://www.netmeds.com/images/cms/offers/1664554617_Netmeds_logo.png',
      'Home delivery available',
      '12 Hours open- Sundays closed',
      'Next available at Tomorrow 9 AM',
      '53rd Street, Billionaires row',
      false,
    ],
    [
      '4',
      'Apollo Pharmacy',
      'https://asset.brandfetch.io/idp07nVFiG/idSyy5orgf.jpeg',
      'Home delivery available',
      '12 Hours open- Sundays closed',
      'Next available at Tomorrow 9 AM',
      '53rd Street, Billionaires row',
      true,
    ],
  ],
};

export default data;
